### ISSUE TITLE
Alacritty in MACOS

### ISSUE THREAD

**Issue by thj1990** [makccr/dot#5]
i use your alacritty config in macos big sur, How to move windows around without any borders ? do you have suggestion for that ?

**Comment by makccr** [comment]
Using Alacritty without borders in MacOS is going to be pretty painful, unless your using a third party window manger. I've used a program called Rectangle for a while, and it's a nice hybrid between a full on tiling window manager, and a more manual Windows like window management system, so that's what I'd tend to recommend. 

If you don't want to use the window manager though, I would just turn borders back on. It doesn't seem worth the trouble without it.
